import assert from "node:assert/strict";
import test from "node:test";

// Loaded through jiti so the module's own extensionless imports resolve the way
// the app resolves them (tsconfig moduleResolution: "bundler").
async function loadSubject() {
  const { createJiti } = await import("jiti");
  return createJiti(import.meta.url).import("./markdown-editor.ts");
}

const DOCUMENT = [
  "---",
  "title: Notes",
  "---",
  "",
  "# Heading",
  "",
  "First paragraph with **bold**.",
  "",
  "- item one",
  "  - nested",
  "",
  "| a | b |",
  "| - | - |",
  "| 1 | 2 |",
  "",
  "```js",
  "const x = 1;",
  "```",
  "",
  "$$",
  "E = mc^2",
  "$$",
  "",
  "---",
  "",
].join("\n");

test("splits a document into renderer-identical blocks", async () => {
  const { parseEditorBlocks } = await loadSubject();
  const { blocks } = parseEditorBlocks(DOCUMENT);

  assert.deepEqual(blocks.map((block) => block.kind), [
    "frontmatter", "heading", "paragraph", "list", "table", "code", "math", "thematicBreak",
  ]);
  assert.equal(blocks[1].source, "# Heading");
  assert.equal(blocks[3].source, "- item one\n  - nested");
  assert.equal(blocks[4].source, "| a | b |\n| - | - |\n| 1 | 2 |");
  assert.equal(blocks[5].source, "```js\nconst x = 1;\n```");
  assert.equal(blocks[6].source, "$$\nE = mc^2\n$$");
});

test("reassembles the document byte for byte, whitespace included", async () => {
  const { parseEditorBlocks, assembleDocument } = await loadSubject();

  assert.equal(assembleDocument(parseEditorBlocks(DOCUMENT)), DOCUMENT);
  // Blank lines between blocks and a trailing newline live in the gaps, never
  // regenerated by a serializer.
  assert.equal(assembleDocument(parseEditorBlocks("a\n\n\n\nb\n")), "a\n\n\n\nb\n");
  assert.equal(assembleDocument(parseEditorBlocks("")), "");
  assert.equal(assembleDocument(parseEditorBlocks("no trailing newline")), "no trailing newline");
});

test("editing one block leaves the rest of the document untouched", async () => {
  const { parseEditorBlocks, assembleDocument, replaceBlockSource } = await loadSubject();
  const document = replaceBlockSource(parseEditorBlocks(DOCUMENT), 2, "First paragraph with *italics*.");

  assert.equal(assembleDocument(document), DOCUMENT.replace("**bold**", "*italics*"));
});

test("inserts and deletes blocks without disturbing neighbours", async () => {
  const { parseEditorBlocks, assembleDocument, insertBlockAfter, deleteBlock } = await loadSubject();
  const base = parseEditorBlocks("# a\n\n# b\n");
  const inserted = insertBlockAfter(base, 0, "paragraph", "middle");
  assert.equal(assembleDocument(inserted), "# a\n\nmiddle\n\n# b\n");

  const deleted = deleteBlock(inserted, 1);
  assert.equal(assembleDocument(deleted), "# a\n\n# b\n");

  // Keys stay positional so React remounts moved blocks instead of reusing them.
  assert.deepEqual(deleted.blocks.map((block) => block.key), ["heading-0", "heading-1"]);
});

test("converts a block between kinds, keeping its text", async () => {
  const { parseEditorBlocks, assembleDocument, convertBlock, shiftHeading } = await loadSubject();

  const paragraphs = convertBlock(parseEditorBlocks("hello"), 0, "heading2");
  assert.equal(assembleDocument(paragraphs), "## hello");

  const list = convertBlock(paragraphs, 0, "list");
  assert.equal(assembleDocument(list), "- hello");

  const quote = convertBlock(list, 0, "blockquote");
  assert.equal(assembleDocument(quote), "> hello");

  const back = convertBlock(quote, 0, "paragraph");
  assert.equal(assembleDocument(back), "hello");

  const fence = convertBlock(parseEditorBlocks("plain text"), 0, "code");
  assert.equal(assembleDocument(fence), "```\nplain text\n```");

  const stripped = convertBlock(parseEditorBlocks("## deep"), 0, "paragraph");
  assert.equal(assembleDocument(stripped), "deep");

  const shifted = shiftHeading(parseEditorBlocks("# title"), 0, 1);
  assert.equal(assembleDocument(shifted), "## title");
  // Levels clamp instead of producing an h4 or an h0.
  assert.equal(assembleDocument(shiftHeading(shifted, 0, 1)), "### title");
  assert.equal(assembleDocument(shiftHeading(shifted, 0, 1)), "### title");
  assert.equal(assembleDocument(shiftHeading(shifted, 0, -1)), "# title");
});

test("serializes rendered HTML back to markdown", async () => {
  const { getBlockSerializer } = await loadSubject();
  const serializer = getBlockSerializer("/repo/docs");

  assert.equal(serializer.serialize("<p><strong>bold</strong> and <em>italics</em> and <code>x</code></p>"),
    "**bold** and *italics* and `x`");
  assert.equal(serializer.serialize("<ul><li>a</li><li>b</li></ul>"), "- a\n- b");
  assert.equal(serializer.serialize('<ul><li><input checked="" disabled="" type="checkbox"> done</li></ul>'),
    "- [x] done");
  assert.equal(serializer.serialize('<pre><code class="language-js">const x = 1;</code></pre>'),
    "```js\nconst x = 1;\n```");
});

test("nested lists survive the round trip through markdown", async () => {
  const { getBlockSerializer, parseEditorBlocks } = await loadSubject();
  const serializer = getBlockSerializer("/repo");

  const markdown = serializer.serialize("<ul><li>parent<ul><li>child</li></ul></li><li>second</li></ul>");
  // Four-space indentation still parses as a sublist of a two-column marker.
  assert.deepEqual(parseEditorBlocks(markdown).blocks.map((block) => block.kind), ["list"]);
  assert.equal(parseEditorBlocks(markdown).blocks[0].source, markdown);
});

test("rebuilds document-relative image and link targets", async () => {
  const { getBlockSerializer } = await loadSubject();
  const serializer = getBlockSerializer("/repo/docs");

  // The preview resolves a relative target into an /api/files/... URL; saving
  // must write the relative one back, not the resolved URL.
  const image = serializer.serialize('<img src="/api/files/repo/docs/img/diagram.png?type=read" alt="diagram">');
  assert.equal(image, "![diagram](img/diagram.png)");

  const link = serializer.serialize('<a href="/api/files/repo/docs/guide/start.md?type=read">start</a>');
  assert.equal(link, "[start](guide/start.md)");

  // A target the editor preserved verbatim wins over any reconstruction.
  const preserved = serializer.serialize('<a href="/api/files/repo/docs/guide/start.md" data-md-href="../guide/start.md">start</a>');
  assert.equal(preserved, "[start](../guide/start.md)");

  // External URLs are passed through untouched.
  assert.equal(serializer.serialize('<a href="https://example.com/a">site</a>'), "[site](https://example.com/a)");
});

test("recovers TeX from rendered KaTeX", async () => {
  const { getBlockSerializer } = await loadSubject();
  const serializer = getBlockSerializer("/repo");

  const inline = "<p>text <span class=\"katex\"><span class=\"katex-mathml\"><math>"
    + "<semantics><annotation encoding=\"application/x-tex\">e = mc^2</annotation></semantics>"
    + "</math></span><span class=\"katex-html\" aria-hidden=\"true\">x</span></span> more</p>";
  assert.equal(serializer.serialize(inline), "text $e = mc^2$ more");

  const display = "<span class=\"katex-display\"><span class=\"katex\"><span class=\"katex-mathml\"><math>"
    + "<semantics><annotation encoding=\"application/x-tex\">E = mc^2</annotation></semantics>"
    + "</math></span><span class=\"katex-html\" aria-hidden=\"true\">x</span></span></span>";
  assert.equal(serializer.serialize(display).trim(), "$$E = mc^2$$");
});

test("code fences keep their language and hard breaks survive", async () => {
  const { getBlockSerializer } = await loadSubject();
  const serializer = getBlockSerializer("/repo");

  assert.equal(serializer.serialize("<pre><code class=\"language-python\">x = 1</code></pre>"),
    "```python\nx = 1\n```");
  assert.equal(serializer.serialize("<p>line one<br>line two</p>"), "line one  \nline two");
});
